services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: kanbanboard_bobe
      POSTGRES_USER: kanbanboard_bobe_user
      POSTGRES_PASSWORD: Password123
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanbanboard_bobe_user -d kanbanboard_bobe"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.local
    environment:
      DB_URL: postgresql://kanbanboard_bobe_user:Password123@db:5432/kanbanboard_bobe
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET_KEY: ""
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env.local
    depends_on:
      - server
    ports:
      - "5173:3000"   # host:container — nginx listens on 3000 in the image

volumes:
  dbdata: